


POST http://api-videos-ufud.onrender.com/videos
Content-Type: application/json


{
  "title": "Esse e o video 01",
  "description": "Esse e o video 01",
  "duration": 180
}

###

GET http://api-videos-ufud.onrender.com/videos



###
GET http://api-videos-ufud.onrender.com/videos/search?search=0



###
PUT  http://api-videos-ufud.onrender.com/videos/d96be055-e081-4f59-8092-20dc054d2701
Content-Type: application/json

{
  "title": "Esse e o video 02",
  "description": "Esse e o video 02",
  "duration": 100
}

###


DELETE http://api-videos-ufud.onrender.com/videos/d96be055-e081-4f59-8092-20dc054d2701
Content-Type: application/json